// ignore_for_file: avoid_print
import 'dart:io';

void main() {
  final lcovFile = File('coverage/lcov.info');
  if (!lcovFile.existsSync()) {
    print(
      'Error: coverage/lcov.info not found. Run flutter test --coverage first.',
    );
    exit(1);
  }

  final lines = lcovFile.readAsLinesSync();
  int totalLines = 0;
  int hitLines = 0;

  for (final line in lines) {
    if (line.startsWith('LF:')) {
      totalLines += int.parse(line.split(':')[1]);
    } else if (line.startsWith('LH:')) {
      hitLines += int.parse(line.split(':')[1]);
    }
  }

  final coverage = (hitLines / totalLines) * 100;
  final date = DateTime.now().toIso8601String();
  final testCount = _countTests();

  final content = '''
// Generated by scripts/generate_stats.dart
// Do not edit manually.
class ProjectStats {
  static const double coverage = ${coverage.toStringAsFixed(2)};
  static const String lastUpdate = '$date';
  static const int totalTests = $testCount;
}
''';

  final outputFile = File('lib/core/constants/project_stats.dart');
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(content);

  print(
    'Project stats updated: ${coverage.toStringAsFixed(2)}% coverage, $testCount tests found.',
  );
}

int _countTests() {
  int count = 0;
  final testDir = Directory('test');
  final integrationDir = Directory('integration_test');
  final testRegExp = RegExp(r'\b(test|testWidgets)\s*\(');

  void scan(Directory dir) {
    if (!dir.existsSync()) return;
    for (final entity in dir.listSync(recursive: true)) {
      if (entity is File && entity.path.endsWith('_test.dart')) {
        final content = entity.readAsStringSync();
        // Remove comments to avoid false positives inside comment blocks
        final cleanContent = content
            .replaceAll(RegExp(r'//.*'), '')
            .replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '');
        count += testRegExp.allMatches(cleanContent).length;
      }
    }
  }

  scan(testDir);
  scan(integrationDir);
  return count;
}
