import 'dart:io';

void main() {
  final lcovFile = File('coverage/lcov.info');
  if (!lcovFile.existsSync()) {
    print('Error: coverage/lcov.info not found. Run flutter test --coverage first.');
    exit(1);
  }

  final lines = lcovFile.readAsLinesSync();
  int totalLines = 0;
  int hitLines = 0;

  for (final line in lines) {
    if (line.startsWith('LF:')) {
      totalLines += int.parse(line.split(':')[1]);
    } else if (line.startsWith('LH:')) {
      hitLines += int.parse(line.split(':')[1]);
    }
  }

  final coverage = (hitLines / totalLines) * 100;
  final date = DateTime.now().toIso8601String();

  final content = '''
// Generated by scripts/generate_stats.dart
// Do not edit manually.
class ProjectStats {
  static const double coverage = ${coverage.toStringAsFixed(2)};
  static const String lastUpdate = '$date';
  static const int totalTests = 125; // Based on current suite
}
''';

  final outputFile = File('lib/core/constants/project_stats.dart');
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(content);

  print('Project stats updated: ${coverage.toStringAsFixed(2)}% coverage');
}
