// Generated by scripts/generate_stats.dart
// Do not edit manually.
class ProjectStats {
  static const double coverage = 100.00;
  static const String lastUpdate = '2026-05-20T23:03:14.322456';
  static const int totalTests = 245;
}
