// Generated by scripts/generate_stats.dart
// Do not edit manually.
class ProjectStats {
  static const double coverage = 86.87;
  static const String lastUpdate = '2026-09-18T01:49:01.618360';
  static const int totalTests = 299;
}
